services:
  auth_api:
    container_name: auth_api
    build:
      context: .
      dockerfile: auth_api/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - auth_api_data:/app
    develop:
      watch:
        - action: sync
          path: ./auth_api
          target: /app

  users_api:
    container_name: users_api
    depends_on:
      - auth_api
    build:
      context: .
      dockerfile: users_api/Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - users_api_data:/app
    develop:
      watch:
        - action: sync
          path: ./users_api
          target: /app

  todo_api:
    container_name: todo_api
    depends_on:
      - users_api
    build:
      context: .
      dockerfile: todo_api/Dockerfile
    ports:
      - "8002:8000"
    volumes:
      - todo_api_data:/app
    develop:
      watch:
        - action: sync
          path: ./users_api
          target: /app

volumes:
  auth_api_data:
  users_api_data:
  todo_api_data:
